# Generated by Django 2.1.5 on 2019-03-22 09:18

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog_Type',
            new_name='BlogType',
        ),
    ]
